version: '3.3'

services:
  influxdb:
    volumes:
      - influxdb_data:/var/lib/influxdb
    image: influxdb:2.0.7
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: admin1234
      DOCKER_INFLUXDB_INIT_ORG: iot
      DOCKER_INFLUXDB_INIT_BUCKET: tema
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: Bh4Od8kk6yBxY4sPqoJqn0tcnPxfaRYOBIIlyxJtCaA8Q6OPRmDLd_BrlT93-qxhV8G-RUCx3uJdaMLtZb3CBQ==
    ports:
      - "8086:8086"

volumes:
  influxdb_data: {}
