version: '3.3'

services:

  influxdb:
    volumes:
      - influxdb_data:/var/lib/influxdb
    image: influxdb:2.0.7
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: admin1234
      DOCKER_INFLUXDB_INIT_ORG: iot
      DOCKER_INFLUXDB_INIT_BUCKET: tema
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: Bh4Od8kk6yBxY4sPqoJqn0tcnPxfaRYOBIIlyxJtCaA8Q6OPRmDLd_BrlT93-qxhV8G-RUCx3uJdaMLtZb3CBQ==
    ports:
      - "8086:8086"

  grafana:
    image: grafana/grafana:latest
    env_file:
      - .env
    depends_on:
      - influxdb
    environment:
      GF_SECURITY_ADMIN_PASSWORD: grafanaSPRC2023
      GF_SECURITY_ADMIN_USER: asistent
    ports:
      - "80:3000"
    # networks:
    #   - database_network
    volumes:
      - grafana_data:/var/lib/grafana
    restart: always

  mosquitto:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
    # networks:
    #   - broker_network
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
    restart: always

  adapter:
    build:
      context: .
      dockerfile: ./adapter/Dockerfile
    image: adapter
    env_file:
      - .env
    depends_on:
      - mosquitto
      - influxdb
    environment:
      DEBUG_DATA_FLOW: "true"
      INFLUXDB_URL: ${INFLUXDB_URL}
      INFLUXDB_TOKEN: ${INFLUXDB_TOKEN}
      INFLUXDB_ORG: ${INFLUXDB_ORG}
      INFLUXDB_BUCKET: ${INFLUXDB_BUCKET}
    # networks:
    #   - broker_network
    #   - database_network
    restart: always

volumes:
  influxdb_data: {}
  grafana_data: {}

# networks:
#   broker_network: {}
#   database_network: {}
#   grafana_network: {}
