version: '3.3'

services:

  influxdb:
    image: influxdb:latest
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: admin1234
      DOCKER_INFLUXDB_INIT_ORG: iot
      DOCKER_INFLUXDB_INIT_BUCKET: tema
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: Bh4Od8kk6yBxY4sPqoJqn0tcnPxfaRYOBIIlyxJtCaA8Q6OPRmDLd_BrlT93-qxhV8G-RUCx3uJdaMLtZb3CBQ==
    ports:
      - "8086:8086"
    # networks:
    #   - database_network
    #   - broker_network
    volumes:
      - influxdb_data:/var/lib/influxdb

  grafana:
    image: grafana/grafana:latest
    depends_on:
      - influxdb
    environment:
      GF_SECURITY_ADMIN_PASSWORD: grafanaSPRC2023
      GF_SECURITY_ADMIN_USER: asistent
    ports:
      - "80:3000"
    # networks:
    #   - broker_network
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards

  mosquitto:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
    # networks:
    #   - broker_network
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
    restart: always

  adapter:
    build:
      context: .
      dockerfile: ./adapter/Dockerfile
    image: adapter
    depends_on:
      - mosquitto
      - influxdb
    environment:
      DEBUG_DATA_FLOW: "true"
      INFLUXDB_URL: "http://influxdb:8086"
      INFLUXDB_TOKEN: Bh4Od8kk6yBxY4sPqoJqn0tcnPxfaRYOBIIlyxJtCaA8Q6OPRmDLd_BrlT93-qxhV8G-RUCx3uJdaMLtZb3CBQ==
      INFLUXDB_ORG: iot
      INFLUXDB_BUCKET: tema
    # networks:
    #   - broker_network
    #   - database_network

volumes:
  influxdb_data: {}
  grafana_data: {}

# networks:
#   broker_network: {}
#   database_network: {}
